services:

   # конфигурация для сервисов по умолчанию в *этом* файле
   _defaults:
      autowire: true      # Автоматически внедряет зависимости в ваши сервисы.
      autoconfigure: true # Автоматически регистрирует ваши сервисы как команды, подписчики событий и т.д.

   Maris\Symfony\Mapbox\Service\MapboxDirectionService:
      arguments:
         $apiKey: '%direction.mapbox.token%'
         $client: '@http_client'


