services:

   # конфигурация для сервисов по умолчанию в *этом* файле
   _defaults:
      autowire: true      # Автоматически внедряет зависимости в ваши сервисы.
      autoconfigure: true # Автоматически регистрирует ваши сервисы как команды, подписчики событий и т.д.

   mapbox.directions.service:
      alias: Maris\Symfony\Mapbox\Directions\DirectionService

   mapbox.directions.request_factory:
      alias: Maris\Symfony\Mapbox\Directions\DirectionsRequestFactory

   # Сервис для создания объекта запроса маршрута
   Maris\Symfony\Mapbox\Directions\DirectionsRequestFactory:
      arguments:
         $defaultRequestData: '%direction.mapbox.request%'

   # Сервис для получения маршрутов движения
   Maris\Symfony\Mapbox\Directions\DirectionsService:
      arguments:
         $apiKey: '%direction.mapbox.token%'
         $client: '@http_client'
         $requestFactory: '@mapbox.directions.request_factory'